# Generated by Django 4.2.17 on 2024-12-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Active', (('Active_1', 'Active 1'), ('Active_2', 'Active 2'), ('Active_3', 'Active 3'))), ('Passive', (('Passive_1', 'Passive 1'), ('Passive_2', 'Passive 2'), ('Passive_3', 'Passive 3')))], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
