# Generated by Django 4.2.17 on 2024-12-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Active', (('Transistors', 'Transistors'), ('Diodes', 'Diodes'), ('Microcontrollers', 'Microcontrollers'), ('OPAMPS', 'OPAMPS'), ('Regulators', 'Regulators'), ('Musfets', 'Musfets'), ('IGBTS', 'IGBTS'), ('BRIDGE Rectifiers', 'BRIDGE Rectifiers'))), ('Electronics', (('Computers', 'Computers'), ('Mobile Phones', 'Mobile Phones'), ('Accessories', 'Accessories'))), ('Food', (('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Snacks', 'Snacks')))], max_length=200),
        ),
    ]
