# Generated by Django 5.2.2 on 2025-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Active', [('Transistors', 'Transistors'), ('Diodes', 'Diodes'), ('Microcontrollers', 'Microcontrollers'), ('OPAMPS', 'OPAMPS'), ('Regulators', 'Regulators'), ('Musfets', 'Musfets'), ('IGBTS', 'IGBTS'), ('BRIDGE Rectifiers', 'BRIDGE Rectifiers')])], max_length=200),
        ),
    ]
