# Generated by Django 5.2.2 on 2025-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
