# Generated by Django 5.2.2 on 2025-08-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_product_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
