# Generated by Django 5.2.2 on 2025-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Active', [('Transistors', 'Transistors'), ('Resistors', 'Resistors'), ('Diodes', 'Diodes'), ('Microcontrollers', 'Microcontrollers'), ('OPAMPS', 'OPAMPS'), ('Regulators', 'Regulators'), ('Musfets', 'Musfets'), ('IGBTS', 'IGBTS'), ('BRIDGE Rectifiers', 'BRIDGE Rectifiers')])], max_length=200),
        ),
    ]
