# Generated by Django 4.2.17 on 2024-12-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar1.jpg', upload_to='Profile_Images'),
        ),
    ]
